version: 2
updates:
  - package-ecosystem: npm
    directory: /isogate-genesis
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /isogate-api
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
